config/routes.rb
Rails.application.routes.draw do
  resources :lists 
  root 'lists#index'
  get 'home/delete_all'
  get 'home/delete_crossed'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
	validates :task, presence: true
	
	validates :status, inclusion: { in: [ true, false ] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def delete_all
	    @delete_all = List.destroy_all
	    respond_to do |format|
	      format.html { redirect_to lists_url, notice: 'All tasks was successfully destroyed.' }
	      format.json { head :no_content }
	    end  
  	end
  	def delete_crossed
		@delete_crossed = List.where(:status => true).destroy_all
		redirect_to root_url, notice: 'All completed tasks were successfully destroyed' 
	end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  def index
    @lists = List.all.order('status ASC, created_at DESC')
    @list = List.new
     
  end


  def show
  end

  def new
    @list = List.new
  end


  def edit
  end


  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to root_url, notice: 'Task  was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to root_url, notice: 'Task  was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end



  private
    def set_list
      @list = List.find(params[:id])
    end

    def list_params
      params.require(:list).permit(:task, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <section class="navbar-section">
      <%= render 'lists/navbar'%>
    </section>
    <div class="body-container">
      <%= render 'lists/flash' %>     
    <%= yield %>
    </div>
    
  </body>
</html>

app/views/lists/_add_form.html.erb
<%= form_for(@list) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
        <% @list.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-inline my-2 my-lg-0">
    <%= f.text_field :task, placeholder: 'Agrega tu tarea',  class: 'form-control mr.sm-2', autofocus:true%>
    <%= f.submit 'Add Task', class: 'btn btn-outline-primary'%>
  </div>
<% end %>

app/views/lists/_flash.html.erb
<br/>
<% flash.each do |name, msg|%>
	<div class="alert alert-warning alert-dismissible fade show" >
		<%= content_tag(:div, msg) %>
		 <button type="button" class="close" data-dismiss="alert">&times;</button>	
	</div>
<% end %>	

app/views/lists/_form.html.erb
<div class="center">
  <%= form_for(@list) do |f| %>
    <% if @list.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>
        <ul>
          <% @list.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  <div class="field">
    <%= f.label 'Task'%>
    <%= f.text_field :task , class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.check_box :status , class: "form-check-label"%>
  </div>
  <div class="center">
    <%= f.submit 'Update Task',  class:"btn btn-primary mb-2"%>
  </div>
  <% end %>
</div>

app/views/lists/_navbar.html.erb
	<nav id="navbar" class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
	  <%= link_to 'Nagûûra To-Do List', root_path, class: 'navbar-brand' %>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>

	  <div class="navbar-collapse" id="navbarSupportedContent">
	    <ul class="navbar-nav ml-auto">
	    	 <%= link_to 'New Custom Task', new_list_path , class: 'btn btn-outline-info'%> 
	    </ul>
	    	<%= render 'add_form' %>
	  </div>
	</nav>

app/views/lists/edit.html.erb
<header id="header-edit" class="header-edit">
	<h2 class="title-edit">Edit Your Task </h2>
</header>

<div class="section-edit">
	<div class="container">
		<div class="center">
			<%= render 'form', list: @list %>
		</div>
	</div>
</div>
<div class="center">
	<%= link_to 'Show Task', @list, class: 'show' %> |
	<%= link_to 'Back to Tasks', lists_path, class: 'back' %>
</div>

app/views/lists/index.html.erb
<header id="header" class="header">
  <h2 class="title">Tasks</h2>
</header>

<div class="container">
  <table id="principal-table" class="table table-hover ">
    <tbody>
      <% @lists.each do |list| %>
        <% if list.status %>
          <tr class="table-secondary">
            <td class="striker"><%= link_to list.task, edit_list_path(list)%></td>
            <td >
              <center>
                <%= form_for(list) do |f| %>
                <%= f.text_field :task, type: 'hidden'%>
                <%= f.check_box :status, :checked => false, :style => 'visibility: hidden'%>
                <%= f.submit "Completed Task", class:"btn btn-outline-secondary "%>
                <% end%>
              </center>  
            </td>
            <td>
                <%= link_to 'Delete', list,class: 'btn btn-outline-warning',
                                      method: :delete,data: {confirm: 'Are u sure?'} %> 
            </td>
          </tr>
        <% else%>
          <tr >
            <td class="striker-1"><%= link_to list.task, edit_list_path(list)%></td>
            <td>
              <center>
                <%= form_for(list) do |f| %>
                <%= f.text_field :task, type: 'hidden'%>
                <%= f.check_box :status, :checked => true, :style => 'visibility: hidden'%>
                <%= f.submit "Complete Task", class:'btn btn-outline-secondary' %>
                <% end%>
              </center>
            </td>
            <td>
                <%= link_to 'Delete', list,class: 'btn btn-outline-danger', 
                                        method: :delete,data: { confirm: 'Are you sure?'} %>
            </td>
          </tr>
        <% end%>
      <% end %>
    </tbody>
  </table>
</div>

<div class="container">
  <div class="center">
    <%= link_to 'Destroy all Tasks', home_delete_all_path ,class: 'btn btn-outline-danger', data: { confirm: 'Are you sure?'}%> 
    <%= link_to 'Destroy all completed Tasks', home_delete_crossed_path,class: 'btn btn-outline-danger',  data: { confirm: 'Are you sure?'} %>
  </div>
</div>
<footer id="footer">
  <div class="center">
    <p>
      &copy: To-do By Nagûûra
    </p>
  </div>
  
</footer>

app/views/lists/new.html.erb
<div class="container-new">
	<div class="container">
		<header id="header-edit" class="header-edit">
			<h2 class="title-edit">New Custom Task </h2>
		</header>

		<div class="center">
			  <%= form_for(@list) do |f| %>
			    <% if @list.errors.any? %>
			      <div id="error_explanation">
			        <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>
			        <ul>
			          <% @list.errors.full_messages.each do |message| %>
			            <li><%= message %></li>
			          <% end %>
			        </ul>
			      </div>
			    <% end %>
			  <div class="field">
				    <%= f.label 'Task'%>
				    <%= f.text_field :task , class: 'form-control' %>
			  </div>

			  <div class="field">
			    	<%= f.check_box :status , class: "form-check-label"%>
			  </div>

			  <div class="center">
			    	<%= f.submit 'Create Task',  class:"btn btn-primary mb-2"%>
			  </div>
			  <% end %>
		</div>

		<div class="center">
			<%= link_to 'Back to Tasks', lists_path, class: 'back' %>
		</div>
	</div>
</div>

app/views/lists/show.html.erb
<div class="center">
	<div class="section-show">
		<div class="container">
			<div class="p-3 mb-2 bg-white text-dark"> 
				<strong>Task:</strong> <br/> 
				<%= @list.task %> 
			</div>
			
			<div class="p-3 mb-2 bg-white text-dark"> 
				<strong>Task Status:</strong> <br/>
				<% if @list.status %>
					Completed 
				<%else%>
					Uncompleted
				<%end%>
			</div>
		</div>
	</div>
	<div class="center">
		<%= link_to 'Edit Task', edit_list_path(@list), class: 'show' %> |
		<%= link_to 'Back to Tasks', lists_path, class: 'back' %>
	</div>	
</div>